<a href="https://colab.research.google.com/github/joannamickamedina/DSA-58010/blob/main/Array_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
#Create an array of number elements

num = [1,2,3]

print(num)

[1, 2, 3]


In [14]:
#Create an array of number elements
import numpy as np
number = np.array([1,2,3,4]) #3x3 matrix

print(number)

[1 2 3 4]


In [15]:
#Create an array of number elements
import numpy as np
number = np.array([[1,2,3,4],
                  [5,6,7,8]]) #3x3 matrix

print(number)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
#Create an array of number elements

number = [1,2,3]
for x in number:
  print(x)

1
2
3


In [1]:
#Create an array of elements pertaining to animals

animals = ["dog","cat","fish"]
for x in animals:
  print(x)

dog
cat
fish


In [2]:
animals = ["dog","cat","fish"]
x=animals[0]
print(x)

dog


In [3]:
animals = ["dog","cat","fish"]
x=animals[0]
x2=animals[1]
print(x)
print(x2)

dog
cat


In [8]:
#Inserting Array Elements
animals = ["dog","cat","fish"]
animals.append("monkeys")
print(animals)

['dog', 'cat', 'fish', 'monkeys']


In [4]:
#Modifying Array Elements
animals = ["dog","cat","fish"]
animals[2] = "monkeys"
print(animals)

['dog', 'cat', 'monkeys']


In [9]:
#Removing Array Elements
animals = ["dog","cat","fish"]
animals.pop(2)
print(animals)

['dog', 'cat']


In [10]:
#Looping Array Elements
animals = ["dog","cat","fish"]
for x in animals:
  if x=="cat":
    print(x)

cat


In [11]:
#Looping Array Elements
animals = ["dog","cat","fish"]
for x in animals:
    print(x)
    if x=='cat':
      break

dog
cat


In [12]:
#Length of Array
animals = ["dog","cat","fish"]
x=len(animals)
print(x)

3
